name: Labeler

on:
  workflow_call:

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Auto Label PRs
        uses: actions/labeler@v4
        with:
          configuration-path: .github/labeler.yml